help
  @echo please enter the component name which is consider as a 1st argument

frontend: ## install frontend components
  @sh components/frontend.sh

catalogue: ## install catalogue components
  @sh components/catalogue.sh

cart: ## install cart components
  @sh components/cart.sh

user: ## install user components
  @sh components/user.sh

shipping: ## install shipping components
  @sh components/shipping.sh

payment: ## install payment components
  @sh components/payment.sh

mongodb ## install mongodb components
  @sh components/mongodb.sh

mysql: ## install mysql components
  @sh components/mysql.sh

radis: ## install radis components
  @sh components/radis.sh

rabbitmq: ## install rabbitmq components
  @sh components/rabbitmq.sh