
frontend : ## Install Frontend components
	@sh components/frontend.sh

catalogue :## Install catalogue components
	@sh components/catalaouge.sh

cart : ## Install cart components
	@sh components/cart.sh

user : ## Install user components
	@sh components/user.sh

shipping : ## Install shipping components
	@sh components/shipping.sh

payment : ## Install payment components
	@sh components/payment.sh

mongodb : ## Install mongodb components
	@sh components/mongodb.sh

mysql : ## Install mysql components
	@sh components/mysql.sh

redis : ## Install redis components
	@sh components/redis.sh

rabbitmq : ## Install rabbitmq components
	@sh components/rabbitmq.sh
